root = "."
tmp_dir = "tmp"

[build]
bin = "/src/tmp/server"
cmd = "/src/scripts/generate_protobuf.sh && go build -o /src/tmp/server /src/cmd/server/"
delay = 500
exclude_dir = ["tmp", "vendor", "docs"]
exclude_file = []
exclude_regex = ["_test.go", ".pb.go"]
exclude_unchanged = false
follow_symlink = false
full_bin = ""
include_dir = []
include_ext = ["go", "proto"]
kill_delay = "0s"
log = "build-errors.log"
send_interrupt = false
stop_on_error = true

[color]
app = "API"
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
time = false

[misc]
clean_on_exit = false

[screen]
clear_on_rebuild = false
keep_scroll = true
