root = "."
tmp_dir = "tmp"

[build]
bin = "/go/bin/sqlc generate -f /src/internal/db/sqlc.yaml"
cmd = "/bin/true"
delay = 500
exclude_dir = []
exclude_file = []
exclude_regex = ["_test.go", ".pb.go", ".go"]
exclude_unchanged = false
follow_symlink = false
full_bin = ""
include_dir = ["internal/db"]
include_ext = ["go", "sql"]
kill_delay = "0s"
log = "build-errors.log"
send_interrupt = false
stop_on_error = true

[color]
app = "sqlc"
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
time = false

[misc]
clean_on_exit = false

[screen]
clear_on_rebuild = false
keep_scroll = true
